global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
  - job_name: 'varnish'
    static_configs:
      - targets: ['varnish:9131']